# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Publish package to the Maven Central Repository

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v1
        with:
          java-version: 13
#           server-id: ossrh
#           server-username: ${{ secrets.MAVEN_USERNAME }}
#           server-password: ${{ secrets.MAVEN_PASSWORD }}
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
#           gpg-passphrase: ${{ secrets.MAVEN_GPG_PASS_PHRASE }}
      - name: Publish package
        run: |
          echo '${{ secrets.MAVEN_M2_SETTINGS }}' > /home/runner/.m2/settings.xml
          cat /home/runner/.m2/settings.xml
          mvn deploy -Dgpg.passphrase=${{ secrets.MAVEN_GPG_PASS_PHRASE }}
